on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
      - ".gitmodules"
      - "io.github.g0orx.linhpsdr.*"
      - "*.patch"
  pull_request:
    branches:
    - main
    paths:
      - ".gitmodules"
      - "io.github.g0orx.linhpsdr.*"
      - "*.patch"

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - shell: bash
        run: |
          echo -n "${{ secrets.FLATPAK_REPO_SIGNING_KEY_HOME }}" | base64 -d | tar -xzf -
          git submodule update --init --recursive
      - uses: dagger/dagger-for-github@d913e70051faf3b907d4dd96ef1161083c88c644 # v8.2.0
        with:
          version: "v0.18.16" # Upgrade to .18 once https://github.com/dagger/dagger/pull/11011 is merged
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
          verb: call
          args: >-
            --source="."
            --gpg-home-dir=".gpg"
            --gpg-key-id="${{ vars.FLATPAK_REPO_SIGNING_KEY_ID }}"
            repo-directory
            export --path="assets/"
      - uses: dagger/dagger-for-github@d913e70051faf3b907d4dd96ef1161083c88c644 # v8.2.0
        with:
          version: "v0.18.16"
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
          verb: call
          args: >-
            --source="."
            --gpg-home-dir=".gpg"
            --gpg-key-id="${{ vars.FLATPAK_REPO_SIGNING_KEY_ID }}"
            flatpakrepo-file
            export --path="assets/${{ github.ref_name }}.flatpakrepo"
      - id: deployment
        uses: actions/upload-pages-artifact@v4
        with:
          path: assets/

  deploy:
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
