on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - shell: bash
        run: |
          echo "${{ secrets.FLATPAK_REPO_SIGNING_KEY_HOME }}" | base64 -d | tar -xzf -
      - uses: dagger/dagger-for-github@8.0.0
        with:
          version: "latest"
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
          verb: call
          args: |
            --gpg-home-dir=".gpg" \
            --gpg-key-id="${{ vars.FLATPAK_REPO_SIGNING_KEY_ID }}" \
            signed-repo-directory \
            export --path="assets/"
      - id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: assets/

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4